sudo: false
language: node_js
node_js:
  - 'node'
  - 'lts/*'
before_install:
  - npm install -g npm
install:
  - npm install
  - npm install -g codecov
script:
  - npm run validate
after_script:
  - npm run codecov
cache:
  directories:
    - node_modules
